image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - yarn

build_script:
  - yarn dist

deploy_script:
  - ps: |
      $username = "appveyor"
      $password = "Vatt3laPesca!"
      $server = "ftp.intelli-design.co.uk"
      $localFilePath = "/public_html/temp"

      curl -T $localFilePath -u "$username:$password" $server

test: off